files:
  - source: /**/lang/checkout/en.properties
    translation: /**/lang/checkout/%two_letters_code%.properties
  - source: /**/lang/creditcards/en.properties
    translation: /**/lang/creditcards/%two_letters_code%.properties
  - source: /**/lang/mastercard/en.properties
    translation: /**/lang/mastercard/%two_letters_code%.properties
  - source: /**/lang/visa/en.properties
    translation: /**/lang/visa/%two_letters_code%.properties
  - source: /**/lang/amex/en.properties
    translation: /**/lang/amex/%two_letters_code%.properties
